# Generated by Django 2.2 on 2020-02-10 12:06

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mydiplom', '0002_auto_20200210_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1990, 2, 10, 2, 6, 28, 596025), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_IP',
            field=models.GenericIPAddressField(default='get_user_ip', verbose_name='Регистрация с ІР'),
        ),
    ]
