# Generated by Django 2.2 on 2020-02-12 10:59

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mydiplom', '0004_auto_20200210_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Текст заявки'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='priority',
            field=models.CharField(choices=[('Низкая', 'Low'), ('Средняя', 'Medium'), ('Высокая', 'High')], default='Средняя', max_length=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Принятая', 'Принятая'), ('Отклонённая', 'Отклонённая'), ('Окончательно отклонённая', 'Окончательно отклонённая')], default='В обработке', max_length=25),
        ),
        migrations.AlterField(
            model_name='claim',
            name='theme',
            field=models.CharField(choices=[('Не определена', 'Не определена'), ('Гражданские дела', 'Гражданские дела'), ('Уголовные дела', 'Уголовные дела'), ('Бизнес', 'Бизнес')], default='Не определена', max_length=250, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1990, 2, 12, 0, 59, 21, 399525), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Страна проживания'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не определён', 'Не определён')], default='Не определён', max_length=7),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='/images/bydefault/unnamed.png', upload_to='images/', verbose_name='Фотография'),
        ),
    ]
