# Generated by Django 2.2 on 2020-02-12 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiplom', '0005_auto_20200212_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Загрузить документы (один файл)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1990, 2, 12, 1, 47, 19, 945387), verbose_name='Дата рождения'),
        ),
    ]
