# Generated by Django 2.2 on 2020-02-12 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiplom', '0006_auto_20200212_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='priority',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], default='Средняя', max_length=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(blank=True, max_length=40000, null=True, verbose_name='Текст заявки (не более 40 000 знаков)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1990, 2, 12, 2, 22, 20, 961019), verbose_name='Дата рождения'),
        ),
    ]
