# Generated by Django 2.2 on 2020-02-18 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiplom', '0007_auto_20200212_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='first_rejected_comment',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='priority',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], default='Средняя', max_length=10, verbose_name='Степень важности'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Принятая', 'Принятая'), ('Отклонённая', 'Отклонённая'), ('Окончательно отклонённая', 'Окончательно отклонённая')], default='В обработке', max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Комментарий создан'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Комментарий обновлен'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1990, 2, 18, 4, 18, 9, 171843), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не определён', 'Не определён')], default='Не определён', max_length=7, verbose_name='Пол'),
        ),
    ]
